<?php
/**
 * CampaignTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Marketing
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing API
 *
 * ConnectWise Marketing API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Marketing;

/**
 * CampaignTest Class Doc Comment
 *
 * @category    Class */
// * @description Campaign
/**
 * @package     Spinen\ConnectWise\Clients\Marketing
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CampaignTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Campaign"
     */
    public function testCampaign()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "sub_type"
     */
    public function testPropertySubType()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {

    }

    /**
     * Test attribute "end_date"
     */
    public function testPropertyEndDate()
    {

    }

    /**
     * Test attribute "location_id"
     */
    public function testPropertyLocationId()
    {

    }

    /**
     * Test attribute "member"
     */
    public function testPropertyMember()
    {

    }

    /**
     * Test attribute "inactive"
     */
    public function testPropertyInactive()
    {

    }

    /**
     * Test attribute "inactive_days_after_end"
     */
    public function testPropertyInactiveDaysAfterEnd()
    {

    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {

    }

    /**
     * Test attribute "default_group"
     */
    public function testPropertyDefaultGroup()
    {

    }

    /**
     * Test attribute "marketing_manager_default_track_id"
     */
    public function testPropertyMarketingManagerDefaultTrackId()
    {

    }

    /**
     * Test attribute "opportunity_default_track_id"
     */
    public function testPropertyOpportunityDefaultTrackId()
    {

    }

    /**
     * Test attribute "impressions"
     */
    public function testPropertyImpressions()
    {

    }

    /**
     * Test attribute "budget_revenue"
     */
    public function testPropertyBudgetRevenue()
    {

    }

    /**
     * Test attribute "budget_cost"
     */
    public function testPropertyBudgetCost()
    {

    }

    /**
     * Test attribute "actual_cost"
     */
    public function testPropertyActualCost()
    {

    }

    /**
     * Test attribute "budget_gross_margin"
     */
    public function testPropertyBudgetGrossMargin()
    {

    }

    /**
     * Test attribute "budget_roi"
     */
    public function testPropertyBudgetRoi()
    {

    }

    /**
     * Test attribute "actual_revenue"
     */
    public function testPropertyActualRevenue()
    {

    }

    /**
     * Test attribute "actual_gross_margin"
     */
    public function testPropertyActualGrossMargin()
    {

    }

    /**
     * Test attribute "actual_roi"
     */
    public function testPropertyActualRoi()
    {

    }

    /**
     * Test attribute "emails_sent"
     */
    public function testPropertyEmailsSent()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

}
