<?php
/**
 * CampaignAuditTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Marketing
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing API
 *
 * ConnectWise Marketing API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Marketing;

/**
 * CampaignAuditTest Class Doc Comment
 *
 * @category    Class */
// * @description CampaignAudit
/**
 * @package     Spinen\ConnectWise\Clients\Marketing
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CampaignAuditTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CampaignAudit"
     */
    public function testCampaignAudit()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "emails_sent"
     */
    public function testPropertyEmailsSent()
    {

    }

    /**
     * Test attribute "emails_unsent"
     */
    public function testPropertyEmailsUnsent()
    {

    }

    /**
     * Test attribute "documents_created"
     */
    public function testPropertyDocumentsCreated()
    {

    }

    /**
     * Test attribute "email_subject"
     */
    public function testPropertyEmailSubject()
    {

    }

    /**
     * Test attribute "group"
     */
    public function testPropertyGroup()
    {

    }

    /**
     * Test attribute "campaign_id"
     */
    public function testPropertyCampaignId()
    {

    }

    /**
     * Test attribute "created_by"
     */
    public function testPropertyCreatedBy()
    {

    }

    /**
     * Test attribute "date_created"
     */
    public function testPropertyDateCreated()
    {

    }

}
