<?php
/**
 * LinkClickedTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Marketing
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing API
 *
 * ConnectWise Marketing API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Marketing;

/**
 * LinkClickedTest Class Doc Comment
 *
 * @category    Class */
// * @description LinkClicked
/**
 * @package     Spinen\ConnectWise\Clients\Marketing
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LinkClickedTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "LinkClicked"
     */
    public function testLinkClicked()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "campaign_id"
     */
    public function testPropertyCampaignId()
    {

    }

    /**
     * Test attribute "contact_id"
     */
    public function testPropertyContactId()
    {

    }

    /**
     * Test attribute "date_clicked"
     */
    public function testPropertyDateClicked()
    {

    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {

    }

    /**
     * Test attribute "query_string"
     */
    public function testPropertyQueryString()
    {

    }

}
