<?php
/**
 * CampaignFormsSubmittedApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Marketing
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing API
 *
 * ConnectWise Marketing API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Marketing;

use \Spinen\ConnectWise\Clients\Marketing\Configuration;
use \Spinen\ConnectWise\Clients\Marketing\ApiClient;
use \Spinen\ConnectWise\Clients\Marketing\ApiException;
use \Spinen\ConnectWise\Clients\Marketing\ObjectSerializer;

/**
 * CampaignFormsSubmittedApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Marketing
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CampaignFormsSubmittedApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for marketingCampaignsIdFormsSubmittedCountGet
     *
     * .
     *
     */
    public function testMarketingCampaignsIdFormsSubmittedCountGet()
    {

    }

    /**
     * Test case for marketingCampaignsIdFormsSubmittedFormSubmittedIdDelete
     *
     * .
     *
     */
    public function testMarketingCampaignsIdFormsSubmittedFormSubmittedIdDelete()
    {

    }

    /**
     * Test case for marketingCampaignsIdFormsSubmittedFormSubmittedIdGet
     *
     * .
     *
     */
    public function testMarketingCampaignsIdFormsSubmittedFormSubmittedIdGet()
    {

    }

    /**
     * Test case for marketingCampaignsIdFormsSubmittedFormSubmittedIdPatch
     *
     * .
     *
     */
    public function testMarketingCampaignsIdFormsSubmittedFormSubmittedIdPatch()
    {

    }

    /**
     * Test case for marketingCampaignsIdFormsSubmittedFormSubmittedIdPut
     *
     * .
     *
     */
    public function testMarketingCampaignsIdFormsSubmittedFormSubmittedIdPut()
    {

    }

    /**
     * Test case for marketingCampaignsIdFormsSubmittedGet
     *
     * .
     *
     */
    public function testMarketingCampaignsIdFormsSubmittedGet()
    {

    }

    /**
     * Test case for marketingCampaignsIdFormsSubmittedPost
     *
     * .
     *
     */
    public function testMarketingCampaignsIdFormsSubmittedPost()
    {

    }

}
