<?php
/**
 * CampaignAuditsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Marketing
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing API
 *
 * ConnectWise Marketing API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Marketing;

use \Spinen\ConnectWise\Clients\Marketing\Configuration;
use \Spinen\ConnectWise\Clients\Marketing\ApiClient;
use \Spinen\ConnectWise\Clients\Marketing\ApiException;
use \Spinen\ConnectWise\Clients\Marketing\ObjectSerializer;

/**
 * CampaignAuditsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Marketing
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CampaignAuditsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for marketingCampaignsIdAuditsAuditIdDelete
     *
     * .
     *
     */
    public function testMarketingCampaignsIdAuditsAuditIdDelete()
    {

    }

    /**
     * Test case for marketingCampaignsIdAuditsAuditIdGet
     *
     * .
     *
     */
    public function testMarketingCampaignsIdAuditsAuditIdGet()
    {

    }

    /**
     * Test case for marketingCampaignsIdAuditsAuditIdPatch
     *
     * .
     *
     */
    public function testMarketingCampaignsIdAuditsAuditIdPatch()
    {

    }

    /**
     * Test case for marketingCampaignsIdAuditsAuditIdPut
     *
     * .
     *
     */
    public function testMarketingCampaignsIdAuditsAuditIdPut()
    {

    }

    /**
     * Test case for marketingCampaignsIdAuditsCountGet
     *
     * .
     *
     */
    public function testMarketingCampaignsIdAuditsCountGet()
    {

    }

    /**
     * Test case for marketingCampaignsIdAuditsGet
     *
     * .
     *
     */
    public function testMarketingCampaignsIdAuditsGet()
    {

    }

    /**
     * Test case for marketingCampaignsIdAuditsPost
     *
     * .
     *
     */
    public function testMarketingCampaignsIdAuditsPost()
    {

    }

}
