<?php
/**
 * CampaignSubTypesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Marketing
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing API
 *
 * ConnectWise Marketing API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Marketing;

use \Spinen\ConnectWise\Clients\Marketing\Configuration;
use \Spinen\ConnectWise\Clients\Marketing\ApiClient;
use \Spinen\ConnectWise\Clients\Marketing\ApiException;
use \Spinen\ConnectWise\Clients\Marketing\ObjectSerializer;

/**
 * CampaignSubTypesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Marketing
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CampaignSubTypesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for marketingCampaignsTypesIdSubTypesCountGet
     *
     * .
     *
     */
    public function testMarketingCampaignsTypesIdSubTypesCountGet()
    {

    }

    /**
     * Test case for marketingCampaignsTypesIdSubTypesGet
     *
     * .
     *
     */
    public function testMarketingCampaignsTypesIdSubTypesGet()
    {

    }

    /**
     * Test case for marketingCampaignsTypesIdSubTypesPost
     *
     * .
     *
     */
    public function testMarketingCampaignsTypesIdSubTypesPost()
    {

    }

    /**
     * Test case for marketingCampaignsTypesIdSubTypesSubTypeIdDelete
     *
     * .
     *
     */
    public function testMarketingCampaignsTypesIdSubTypesSubTypeIdDelete()
    {

    }

    /**
     * Test case for marketingCampaignsTypesIdSubTypesSubTypeIdGet
     *
     * .
     *
     */
    public function testMarketingCampaignsTypesIdSubTypesSubTypeIdGet()
    {

    }

    /**
     * Test case for marketingCampaignsTypesIdSubTypesSubTypeIdPatch
     *
     * .
     *
     */
    public function testMarketingCampaignsTypesIdSubTypesSubTypeIdPatch()
    {

    }

    /**
     * Test case for marketingCampaignsTypesIdSubTypesSubTypeIdPut
     *
     * .
     *
     */
    public function testMarketingCampaignsTypesIdSubTypesSubTypeIdPut()
    {

    }

}
