<?php
/**
 * CampaignLinksClickedApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Marketing
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing API
 *
 * ConnectWise Marketing API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Marketing;

use \Spinen\ConnectWise\Clients\Marketing\Configuration;
use \Spinen\ConnectWise\Clients\Marketing\ApiClient;
use \Spinen\ConnectWise\Clients\Marketing\ApiException;
use \Spinen\ConnectWise\Clients\Marketing\ObjectSerializer;

/**
 * CampaignLinksClickedApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Marketing
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CampaignLinksClickedApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for marketingCampaignsIdLinksClickedCountGet
     *
     * .
     *
     */
    public function testMarketingCampaignsIdLinksClickedCountGet()
    {

    }

    /**
     * Test case for marketingCampaignsIdLinksClickedGet
     *
     * .
     *
     */
    public function testMarketingCampaignsIdLinksClickedGet()
    {

    }

    /**
     * Test case for marketingCampaignsIdLinksClickedLinkClickedIdDelete
     *
     * .
     *
     */
    public function testMarketingCampaignsIdLinksClickedLinkClickedIdDelete()
    {

    }

    /**
     * Test case for marketingCampaignsIdLinksClickedLinkClickedIdGet
     *
     * .
     *
     */
    public function testMarketingCampaignsIdLinksClickedLinkClickedIdGet()
    {

    }

    /**
     * Test case for marketingCampaignsIdLinksClickedLinkClickedIdPatch
     *
     * .
     *
     */
    public function testMarketingCampaignsIdLinksClickedLinkClickedIdPatch()
    {

    }

    /**
     * Test case for marketingCampaignsIdLinksClickedLinkClickedIdPut
     *
     * .
     *
     */
    public function testMarketingCampaignsIdLinksClickedLinkClickedIdPut()
    {

    }

    /**
     * Test case for marketingCampaignsIdLinksClickedPost
     *
     * .
     *
     */
    public function testMarketingCampaignsIdLinksClickedPost()
    {

    }

}
