<?php
/**
 * GroupContactsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Marketing
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing API
 *
 * ConnectWise Marketing API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Marketing;

use \Spinen\ConnectWise\Clients\Marketing\Configuration;
use \Spinen\ConnectWise\Clients\Marketing\ApiClient;
use \Spinen\ConnectWise\Clients\Marketing\ApiException;
use \Spinen\ConnectWise\Clients\Marketing\ObjectSerializer;

/**
 * GroupContactsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Marketing
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GroupContactsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for marketingGroupsIdContactsContactIdDelete
     *
     * .
     *
     */
    public function testMarketingGroupsIdContactsContactIdDelete()
    {

    }

    /**
     * Test case for marketingGroupsIdContactsContactIdGet
     *
     * .
     *
     */
    public function testMarketingGroupsIdContactsContactIdGet()
    {

    }

    /**
     * Test case for marketingGroupsIdContactsContactIdPatch
     *
     * .
     *
     */
    public function testMarketingGroupsIdContactsContactIdPatch()
    {

    }

    /**
     * Test case for marketingGroupsIdContactsContactIdPut
     *
     * .
     *
     */
    public function testMarketingGroupsIdContactsContactIdPut()
    {

    }

    /**
     * Test case for marketingGroupsIdContactsCountGet
     *
     * .
     *
     */
    public function testMarketingGroupsIdContactsCountGet()
    {

    }

    /**
     * Test case for marketingGroupsIdContactsGet
     *
     * .
     *
     */
    public function testMarketingGroupsIdContactsGet()
    {

    }

    /**
     * Test case for marketingGroupsIdContactsPost
     *
     * .
     *
     */
    public function testMarketingGroupsIdContactsPost()
    {

    }

}
